#!/bin/bash
if [ -z $1 ];
then
    echo "We need the coverity token: e.g. "
    echo  "./pce-submit tHiSiSnOtMyKeY"
    echo  "Ask Ian: iam@csl.sri.com"
    exit 1
else
   COVERITY_TOKEN=$1
fi

rm pce.tgz
tar czvf pce.tgz cov-int
curl --form token=${COVERITY_TOKEN} \
  --form email=iam@csl.sri.com \
  --form file=@pce.tgz \
  --form version="PCE Head" \
  --form description="Probabablistic Consistency Engine" \
  https://scan.coverity.com/builds?project=SRI-CSL%2Fpce
